# Generated by Django 4.1.7 on 2023-04-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0004_remove_message_useridreceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='IsBuy',
            field=models.BooleanField(null=True),
        ),
    ]
