# Generated by Django 4.1.7 on 2023-04-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0005_history_isbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CategoryParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.category'),
        ),
    ]
