# Generated by Django 4.1.7 on 2023-04-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0006_alter_category_categoryparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CategoryParent',
        ),
    ]
