# Generated by Django 4.1.7 on 2023-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0008_product_imgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
