# Generated by Django 4.1.7 on 2023-04-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0012_remove_user_address_remove_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Amount',
        ),
    ]
