# Generated by Django 4.1.7 on 2023-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0013_remove_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
    ]
