# Generated by Django 4.2.1 on 2023-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0017_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='PhoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
