# Generated by Django 4.1.7 on 2023-04-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_history_categoryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='UserIDReceiver',
        ),
    ]
