# Generated by Django 4.1.7 on 2023-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='PhoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
