# Generated by Django 4.1.7 on 2023-04-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0014_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Price',
        ),
    ]
