# Generated by Django 4.2.1 on 2023-05-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0016_remove_message_useridsend_delete_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sales',
            field=models.IntegerField(null=True),
        ),
    ]
