# Generated by Django 4.2.1 on 2023-05-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0018_order_address_order_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Sales',
        ),
    ]
